### ISSUE TITLE
Incorrect value for iPhone5

### ISSUE THREAD

**Issue by dalisoft** [LeaVerou/dpi#179] opened 2016-12-13 14:31 UTC
My phone iphone5 ios10. In demo shows my phone 98ppi and 13.3". I dont think this is correct values as 13.3" isn't a small value. Thanks for amazing library. 
I will be happy to see fix for this

**Comment by LeaVerou** [comment] 2016-12-13 15:29
Duplicate of #32.

**Closed as completed by LeaVerou** 2016-12-13 15:29 UTC
