### ISSUE TITLE
Why are the PPI values hardcoded?

### ISSUE THREAD

**Issue by miguelsousa** [LeaVerou/dpi#24] opened 2013-06-12 02:57 UTC
Instead of hardcoding the ppi values in the screens.json file, why don't you calculate them on-the-fly using the formula below?

``` javascript
ppi = Math.round( Math.sqrt( Math.pow(w,2) + Math.pow(h,2) ) / d )
```

**Comment by LeaVerou** [comment] 2013-06-12 03:00
This is a duplicate of #11.

Besides the reasons outlined there, there’s also another: Because sometimes the computed dpi does not match the one provided by the manufacturer (e.g. iPhone 4).

**Closed as completed by LeaVerou** 2013-06-12 03:00 UTC
